id: I8D6E0102
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T20:43:55+00:00'
last_modified: '2022-06-08T01:59:04.366106+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN3105
  title: བཀའ་གདམས་མེས་པོའི་ཞལ་ལུང་སྐལ་ལྡན་ཤིང་རྟའི་ཆུ་རྒྱུན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E2CB:
      image_group_id: I3CN3113
      title: ''
      total_pages: 536
      order: 1
      base_file: E2CB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
