id: P004566
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN3105
  title: བཀའ་གདམས་མེས་པོའི་ཞལ་ལུང་སྐལ་ལྡན་ཤིང་རྟའི་ཆུ་རྒྱུན།
  author: ''
  volumes:
    4aae50234c894077a4e6779c74f03803:
      image_group_id: I3CN3113
      title: ''
      volume_number: 1
      total_pages: 536
      base_file: v001.txt
